"""Dashboard store facade — re-exports from ``core.dashboard``."""

from __future__ import annotations

from core.dashboard.normalize import (
    _apply_widget_patch,
    _find_page,
    _make_page,
    _make_panel,
    _migrate_to_section_layout,
    _normalize_dashboard_store,
    _normalize_icon,
    _normalize_page_columns,
    _normalize_page_record,
    _normalize_panel_background,
    _normalize_panel_pages,
    _normalize_panel_record,
    _normalize_widget_record,
    _normalize_widget_span,
    _section_panels_only,
    _widget_entity_ids,
    _widget_entity_records,
    reconcile_dashboard_section,
    reconcile_widget_entity_refs,
    sync_widget_entity_ref,
)
from core.dashboard.persistence import (
    _all_panel_widgets,
    _dashboard_section,
    _dashboard_user_prefs,
    _find_panel,
    _find_widget,
    _find_widget_any_page,
    _read_dashboard_raw,
    _save_dashboard,
    _set_user_default_page_id,
    _user_default_page_id,
    _write_dashboard_raw,
)
from core.dashboard.visibility import (
    _evaluate_panel_visibility,
    _evaluate_visibility_condition,
    _evaluate_widget_visibility,
    _panel_visibility_config,
    _widget_renderer,
    _widget_visibility_config,
)

__all__ = [
    "_apply_widget_patch",
    "_find_page",
    "_make_page",
    "_make_panel",
    "_migrate_to_section_layout",
    "_normalize_dashboard_store",
    "_normalize_icon",
    "_normalize_page_columns",
    "_normalize_page_record",
    "_normalize_panel_background",
    "_normalize_panel_pages",
    "_normalize_panel_record",
    "_normalize_widget_record",
    "_normalize_widget_span",
    "_section_panels_only",
    "_widget_entity_ids",
    "_widget_entity_records",
    "reconcile_dashboard_section",
    "reconcile_widget_entity_refs",
    "sync_widget_entity_ref",
    "_all_panel_widgets",
    "_dashboard_section",
    "_dashboard_user_prefs",
    "_find_panel",
    "_find_widget",
    "_find_widget_any_page",
    "_read_dashboard_raw",
    "_save_dashboard",
    "_set_user_default_page_id",
    "_user_default_page_id",
    "_write_dashboard_raw",
    "_evaluate_panel_visibility",
    "_evaluate_visibility_condition",
    "_evaluate_widget_visibility",
    "_panel_visibility_config",
    "_widget_renderer",
    "_widget_visibility_config",
]
